---
title: "Training Log"
---

:::{=html}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-9usAa8m0M+WyW59Ry...cut..." crossorigin="anonymous" referrerpolicy="no-referrer" />
:::

I see everything in life through the prism of mathematics or statistics. It's no different with sports, especially running (or cycling). This blog will be a place where I combine my passion for endurance sports with professional background in data science.  Just as I enjoy solving equations or structuring data models at work, I enjoy applying that same curiosity to my own training. Training logs, race preparation, and performance modeling — all of these can be enriched by numbers, models, and careful analysis.

Another motivation behind starting this blog is that I recently began working with a coach. That gave me an extra push to look deeper into how we are structuring the training, how I’m progressing, and to better understand the “why” behind what we’re doing. It’s not only about following workouts but also about making sense of the bigger picture, seeing how the plan unfolds, and how the numbers reflect adaptation and improvement.

Numbers, when put into context, tell a story: whether I’m adapting, improving, or stepping into risky territory. That’s why each blog post will focus on a specific question and explore how mathematical thinking can bring clarity—whether it’s about training load, heart rate, distance, or other aspects of performance. This blog is my way of sharing that journey—where mountains, trails, and bikes meet mathematics, analytics, and a touch of artistry.

```{=html}
<div class="project-link-container">
    <i class="fab fa-github"></i>
    <span> Check out the full 
    <a href="https://github.com/1312Bravo/TrainingPeaks_customLog" target="_blank"> GitHub repository </a>
    for this project</span>
</div>
```

::: {.blog-card}
[**Track Your Training Smarter - Data**](training_log/data.qmd)  
Keep all your training and daily metrics in one place without lifting a finger. With a Python pipeline connecting Garmin Connect to Google Sheets, your workouts and daily metrics update automatically every day. The result: a complete, always-current record that makes analysis, trend spotting, and make data-driven decisions precise.
:::

::: {.blog-card}
[**Increase your chances of staying away from running injuries**](training_log/relative_training_load.qmd)  
Put today’s training into context by comparing it with your recent history or, looking forward, use that perspective to decide how much load to take on in your next session. The idea is to give yourself a clearer picture of whether you’re pushing into new territory or staying within safe limits. The goal is to help you understand your training load better, catch signs of overtraining early, and reduce the risk of injuries while keeping your progress moving forward.
:::