project:
  type: website

website:
  title: "Urh Peček | Data Science Blog"
  description: "Projects, experiments, and stories in data science and analytics."
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        menu:
          - text: Training Log
            href: projects/training_log.qmd
    right:
      - icon: github
        href: https://github.com/1312Bravo
        target: _blank

format:
  html:
    theme: cosmo  
    css: styles.css
    code-fold: true
    code-overflow: wrap
    highlight-style: github
    font-awesome: true
