project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Urh Peček | Data Science Blog"
  description: "Projects, experiments, and stories in data science and analytics."
  navbar:
    left: 
      - text: Home
        href: index.qmd
    #   - text: Training Log
    #     href: projects/training_log.qmd
    #   - text: Path To UTMB
    #     href: projects\path_to_utmb.qmd
    # right:
    #   - icon: github
    #     href: https://github.com/1312Bravo
    #     target: _blank

format:
  html:
    theme: cosmo  
    css: styles.css
    code-fold: true
    code-overflow: wrap
    highlight-style: github
    font-awesome: true
