project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/training_log.qmd
            text: Training Log

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
