project:
  type: website

website:
  title: "Urh Peček | Data Science Projects Portfolio, Blog & Stories"
  description: "Exploring Data Science & Analytics ideas and writing a blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        menu:
          - href: projects/training_log.qmd
            text: Training Log
    right:
      - icon: github
        href: https://github.com/1312Bravo
        target: _blank

format:
  html:
    theme: cosmo  
    css: styles.css
    code-fold: true
    code-overflow: wrap
    highlight-style: github
