---
title: "Scrape UTMB Race and Runners statistics - Data"
---

:::{=html}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-9usAa8m0M+WyW59Ry...cut..." crossorigin="anonymous" referrerpolicy="no-referrer" />
:::

Rather than manually copying race results and runner statistics, which would be practically impossible for any comprehensive analysis, I needed a scalable way to get data from the UTMB website programmatically. I built a toolkit of Python helper functions to extract and standardize information from UTMB APIs instead of scraping webpages directly.

```{=html}
<div class="project-link-container">
    <i class="fab fa-github"></i>

    <div style="display: flex; flex-direction: column; gap: 6px; margin-left: 6px;">
        <span>
            You can find the full toolkit on the project’s GitHub repository under the
            <a href="https://github.com/1312Bravo/Path-To-UTMB/blob/main/helper_functions/utmb_api.py" target="_blank">
                helper_functions and in the utmb_api.py
            </a> script.
        </span>

        <span>
            The examples how to run the helpers are in the
            <a href="https://github.com/1312Bravo/Path-To-UTMB/blob/main/data/get_data_example.ipynb" target="_blank">
                data/get_data_example.ipyn
            </a> notebook.
        </span>
    </div>
</div>
```

### UTMB API Authentication Token

Some of the richer UTMB data - such as runner UTMB race scores and runner UTMB index information, is not available through basic scraping, but authentication (a sign in to UTMB webiste) is required. I implemented two helper functions that log into the UTMB API via OAuth and retrieve temporary access tokens. These tokens act as session credentials and allow access to endpoints that are not available through anonymous requests.

- Live Access Token – used for retrieving race-level data

```python
utmb_live_access_token = get_utmb_live_access_token(
    utmb_username=utmb_website_login_username, 
    utmb_password=utmb_website_login_password
)
```

- Access Token – used for retrieving runner-level statistics

```python
utmb_access_token = get_utmb_access_token(
    utmb_username=utmb_website_login_username, 
    utmb_password=utmb_website_login_password
)
```

### UTMB Race Results

UTMB race results are retrieved from the official UTMB Live website <a href="https://live.utmb.world/" target="_blank"> https://live.utmb.world/</a> via direct API requests. Since the data comes from the live UTMB service, the function requires a valid Live Access Token for authentication - <code>access_token</code>. The <code>race_year</code> parameter is self-explanatory, while <code>race_id</code> and <code>course_id</code> can be obtained directly from the race URL on the UTMB Live website. 

For example, for the race page <a href="https://live.utmb.world/julianalps/2025/JAT80K" target="_blank"> https://live.utmb.world/julianalps/2025/JAT80K</a> the race results can be retrieved with: 

```python
JAT80K_2025_results = get_race_results(
    race_id = "julianalps", 
    race_year = 2025, 
    course_id = "JAT80K", 
    access_token = utmb_live_access_token
)
```

The function queries the paginated UTMB Live API, combines all result pages, and returns a standardized DataFrame containing race and runner statistics.

### UTMB Runner Statistics

Runner statistics are retrieved from the official UTMB website <a href="https://utmb.world/" target="_blank">https://utmb.world/</a> via direct API requests. Since this data comes from the standard UTMB platform (not the live service), the function requires a regular UTMB Access Token for authentication - <code>access_token</code>. The main input is <code>runner_id</code>, which can be obtained directly from the runner profile URL on the UTMB website.

For example, for the runner profile <a href="https://utmb.world/runner/1410311.tom.evans" target="_blank"> https://utmb.world/runner/1410311.tom.evans</a> the runner statistics can be retrieved with:

```python
tom_evans_stats = get_runner_results(
    runner_id = "1410311.tom.evans", 
    access_token = utmb_access_token
)
```
The function queries the UTMB API and returns a standardized DataFrame containing the runner's historical race results and overall UTMB statistics.